on: [push]

name: build

jobs:
  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          toolchain: nightly
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: nightly
